language: python
python:
- '3.6'
script: "./build"
deploy:
  matrix:
  - provider: lambda
    function_name: saveMyStreams
    region: us-east-1
    role: arn:aws:iam::984814083532:role/lambda_basic_execution
    runtime: python3.6
    module_name: alexa_py
    handler_name: lambda_function.lambda_handler
    zip: "./src"
    access_key_id: AKIAJTORVAMIVMYJNSTQ
    on:
      branch: master
    secret_access_key:
      secure: wIavE47LLUleUV9nHq++5pnPObkRh6/gOhH1oW9VoTyr3C1IG2DAQTBx0iamLNndWsR0Gygs680ysqKJWB+up3X8YH6NskekwmzvEhU0YEJjOjU9SaW1tAJ8tC4pRoDMhfqI7b4JnSI7SWjwgrCju+Q1ijqdgH3d//KD9eJfEah4Elu0sO37t9Z/CagAz5j4cF1AqoX8zQR6HrQP3NqDPdoOpHjjGE+Zn2++K60Lz3gYoO3E+ed59qSpedBWocdMsGjy5wJ0uGXvEcmvqRXUng3LzTWgHe3x6/E8KktTLBRf4FmKEJC65Jjx+AiKRtynZWvbPLT7lUQYQ0sAxkdAyGhK002K+79qmoS73+nmcI5SoqHD1zwFkuhrY0SlljkXXhVfNlKmniwdNGeqr+PBLm5POXTQENZ+RdxO91x7BRb3lUrWgV/piv2gV4crQGC1GAM7GJDfTuUSkj8OV0c1+7L5BK65Rog1urzzVJkgDO4AlmgIl47T13x8AP3obEkFpbWdyAQqPWWAxvHjLqdNOo3xUuMfwIWuKLd1TuCqMpDjj9P9e/WP8AD3n6pRQPabiJHsrYekjVg2coaDQIZiGp2BwQ117G6UIu+tT5SLsykDoUyGhEGTrj48Y9PIt1nsbHcXOFIwxBM+Z5Wb2bnz6xf0l1dE17O/NPXq5wI0uIk=
  - provider: s3
    bucket: alexa-python-vasos
    local-dir: responses
    skip_cleanup: true
    on:
      branch: master
    access_key_id: AKIAJTORVAMIVMYJNSTQ
    secret_access_key:
      secure:
  secret_access_key:
    secure: wIavE47LLUleUV9nHq++5pnPObkRh6/gOhH1oW9VoTyr3C1IG2DAQTBx0iamLNndWsR0Gygs680ysqKJWB+up3X8YH6NskekwmzvEhU0YEJjOjU9SaW1tAJ8tC4pRoDMhfqI7b4JnSI7SWjwgrCju+Q1ijqdgH3d//KD9eJfEah4Elu0sO37t9Z/CagAz5j4cF1AqoX8zQR6HrQP3NqDPdoOpHjjGE+Zn2++K60Lz3gYoO3E+ed59qSpedBWocdMsGjy5wJ0uGXvEcmvqRXUng3LzTWgHe3x6/E8KktTLBRf4FmKEJC65Jjx+AiKRtynZWvbPLT7lUQYQ0sAxkdAyGhK002K+79qmoS73+nmcI5SoqHD1zwFkuhrY0SlljkXXhVfNlKmniwdNGeqr+PBLm5POXTQENZ+RdxO91x7BRb3lUrWgV/piv2gV4crQGC1GAM7GJDfTuUSkj8OV0c1+7L5BK65Rog1urzzVJkgDO4AlmgIl47T13x8AP3obEkFpbWdyAQqPWWAxvHjLqdNOo3xUuMfwIWuKLd1TuCqMpDjj9P9e/WP8AD3n6pRQPabiJHsrYekjVg2coaDQIZiGp2BwQ117G6UIu+tT5SLsykDoUyGhEGTrj48Y9PIt1nsbHcXOFIwxBM+Z5Wb2bnz6xf0l1dE17O/NPXq5wI0uIk=
